{
  "comments": [
    {
      "key": {
        "uuid": "2a536c56_beeee1f8",
        "filename": "JNIHelp.cpp",
        "patchSetId": 1
      },
      "lineNbr": 86,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2015-08-03T18:01:40Z",
      "side": 1,
      "message": "\u003d\u003d -1?",
      "revId": "0149b3a13d77d1ff5d2a228a2e17ce92c8556537",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "2a08cc62_36a4c0be",
        "filename": "JNIHelp.cpp",
        "patchSetId": 1
      },
      "lineNbr": 106,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2015-08-03T18:01:40Z",
      "side": 1,
      "message": "i realize FatalError shouldn\u0027t return, but if we\u0027re being this anal, it seems odd that there\u0027s no free(3).",
      "revId": "0149b3a13d77d1ff5d2a228a2e17ce92c8556537",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}